# Пример конфигурации для forward_monitor
# Переименуйте файл и заполните токены/ID перед запуском

telegram:
  token: "TELEGRAM_BOT_TOKEN"
  chat: "@default_channel_or_chat_id"
  formatting:
    parse_mode: HTML
    disable_preview: true
    attachments: minimal

discord:
  token: "DISCORD_USER_TOKEN"
  token_type: auto  # варианты: auto, user, bot, bearer
  rate_limit:
    per_second: 3.5
    per_minute: 60
    concurrency: 4

network:
  user_agents:
    mobile_ratio: 0.35
  proxies:
    pool:
      - "http://proxy.example:8080"
    telegram:
      pool:
        - "socks5://tg-proxy.example:9050"
    healthcheck:
      url: "https://www.google.com/generate_204"
      timeout: 5
      cooldown: 180

forward:
  defaults:
    filters:
      whitelist:
        - "airdrop"
      blocked_senders:
        - "spammer123"
      allowed_types:
        - text
        - image
    text:
      chips:
        - "🔥"
      headers:
        - "Важные новости"
      footers:
        - "Forward Bot"
      replacements:
        OG: "Original"
        "[скрыть]": ""
    formatting:
      attachments: compact
  channels:
    - discord: 123456789012345678
      telegram: "-1001234567890"
      name: "Основной канал"
      filters:
        blacklist:
          - "maintenance"
      text:
        headers: ["📢 Анонсы"]
        replacements:
          - find: "LFG"
            replace: "Let's go"
          - find: "[link]"
            replace: ""
    - discord: 223456789012345678  # будет использовать chat по умолчанию

runtime:
  poll_every: 300
  state_file: "monitor_state.json"
  delays:
    min: 0.6
    max: 2.5
