# Forward Monitor — полный пример конфигурации.
# Скопируйте файл в config.yml и заполните обязательные поля.

telegram:
  token: "TELEGRAM_BOT_TOKEN"            # обязательный токен бота
  chat: "@fallback_channel"              # чат по умолчанию для пересылки
  rate_limit:
    per_second: 0.8                      # сообщения в секунду (None = авто)
    per_minute: 25                       # сообщения в минуту (0 = без лимита)
    concurrency: 1                       # параллельные запросы Telegram API
    jitter_min_ms: 60                    # минимальная задержка перед запросом
    jitter_max_ms: 200                   # максимальная задержка перед запросом
    cooldown_seconds: 30.0               # пауза при ошибках 429/5xx
  formatting:
    parse_mode: HTML                     # HTML или MarkdownV2
    disable_link_preview: true           # скрывать предпросмотр ссылок
    max_length: 3500                     # обрезать сообщения длиннее лимита
    ellipsis: "…"                        # суффикс усечения (при обрезке)
    attachments_style: minimal           # compact или minimal

discord:
  token: "DISCORD_USER_TOKEN"            # токен пользователя или бота
  token_type: auto                       # auto/user/bot/bearer
  rate_limit:
    per_second: 4.0                      # запросов в секунду (None = авто)
    per_minute: 60                       # запросов в минуту (0 = без лимита)
    concurrency: 4                       # одновременные запросы к Discord
    jitter_min_ms: 40                    # минимальная задержка между запросами
    jitter_max_ms: 160                   # максимальная задержка между запросами
    cooldown_seconds: 30.0               # пауза перед повтором при ошибке

forward:
  defaults:
    filters:                             # базовые фильтры для всех каналов
      whitelist: []                      # ключевые слова для пропуска
      blacklist: []                      # ключевые слова для блокировки
      allowed_senders: []                # разрешённые авторы
      blocked_senders: []                # авторы под запретом
      allowed_types: []                  # допустимые типы (text,image,…)
      blocked_types: []                  # типы, которые отбрасываем
    text:                                # оформление текста по умолчанию
      chips: []                          # "чипы" перед заголовком
      headers: []                        # строки перед телом сообщения
      footers: []                        # строки после тела сообщения
      replacements: {}                   # find/replace до форматирования
    formatting:                          # уточнение Telegram-профиля
      parse_mode: HTML                   # наследуется из telegram.formatting
      disable_link_preview: true         # наследуется, можно переопределить
      max_length: 3500                   # лимит символов для сегмента
      ellipsis: "…"                      # суффикс при усечении
      attachments_style: minimal         # compact/minimal вывод вложений
  channels:
    - discord: 123456789012345678        # ID канала Discord
      telegram: "-1001234567890"         # чат Telegram для пересылки
      name: "#announcements"             # опциональная метка для логов
      filters:                           # переопределение фильтров
        whitelist: []
        blacklist: ["maintenance"]
        allowed_senders: []
        blocked_senders: []
        allowed_types: []
        blocked_types: []
      text:                              # точечные правки текста
        chips: ["🔥"]
        headers: ["📢 Анонсы"]
        footers: ["Forward Bot"]
        replacements:
          "LFG": "Let's go"
          "[link]": ""
      formatting:
        parse_mode: HTML
        disable_link_preview: false
        max_length: 3500
        ellipsis: "…"
        attachments_style: compact
    - discord: 223456789012345678        # без telegram — возьмётся fallback чат
      telegram: "@fallback_channel"
      name: null
      filters:
        whitelist: []
        blacklist: []
        allowed_senders: []
        blocked_senders: []
        allowed_types: []
        blocked_types: []
      text:
        chips: []
        headers: []
        footers: []
        replacements: {}
      formatting:
        parse_mode: HTML
        disable_link_preview: true
        max_length: 3500
        ellipsis: "…"
        attachments_style: minimal

network:
  user_agents:
    desktop: []                          # пусто = использовать встроенные UA
    mobile: []                           # пусто = использовать встроенные UA
    mobile_ratio: 0.35                   # шанс выбрать мобильный UA
  proxies:
    pool: []                             # общий пул прокси (http/https/socks)
    username: null                       # базовый логин, если требует провайдер
    password: null                       # базовый пароль для прокси
    rotate_url: null                     # URL смены IP для общего пула
    discord:                             # переопределения для Discord
      pool: []
      username: null
      password: null
      rotate_url: null
    telegram:                            # переопределения для Telegram
      pool: []
      username: null
      password: null
      rotate_url: null
    credentials: null                    # auth в формате user:pass
    healthcheck:                         # проверка доступности прокси
      url: "https://www.google.com/generate_204"
      timeout: 5.0
      cooldown: 180.0

runtime:
  poll_every: 300                        # пауза между опросами Discord (сек)
  state_file: "monitor_state.json"       # путь к файлу состояния
  max_messages: 1000                     # максимум сообщений за цикл канала
  max_fetch_seconds: 5.0                 # предел ожидания Discord API
  delays:
    min: 0.5                             # минимальная задержка перед отправкой
    max: 2.0                             # максимальная задержка перед отправкой
