# Forward Monitor — пример минималистичной конфигурации
# Скопируйте файл в config.yml и заполните обязательные поля.

telegram:
  token: "TELEGRAM_BOT_TOKEN"
  chat: "@default_channel_or_chat_id"
  formatting:
    parse_mode: HTML
    disable_preview: true
    attachments: minimal

discord:
  token: "DISCORD_USER_TOKEN"
  token_type: auto  # допустимые значения: auto, user, bot, bearer
  rate_limit:
    per_second: 3.5
    per_minute: 60
    concurrency: 4
    jitter_min_ms: 40
    jitter_max_ms: 160
    cooldown_seconds: 30

forward:
  defaults:
    text:
      headers:
        - "📢 Новости"
      chips:
        - "🔥"
      footers:
        - "Forward Bot"
      replacements:
        "[скрыть]": ""
        OG: "Original"
    filters:
      whitelist:
        - "airdrop"
      blocked_senders:
        - "spammer123"
      allowed_types:
        - text
        - image
    formatting:
      attachments: compact
  channels:
    - name: "#announcements"
      discord: 123456789012345678
      telegram: "-1001234567890"
      filters:
        blacklist:
          - "maintenance"
      text:
        headers:
          - "📢 Анонсы"
        replacements:
          - find: "LFG"
            replace: "Let's go"
          - find: "[link]"
            replace: ""
    - discord: 223456789012345678  # fallback-чат будет использован автоматически

network:
  user_agents:
    mobile_ratio: 0.35
  proxies:
    pool:
      - "http://proxy.example:8080"
    telegram:
      pool:
        - "socks5://tg-proxy.example:9050"
    healthcheck:
      url: "https://www.google.com/generate_204"
      timeout: 5
      cooldown: 180

runtime:
  poll_every: 300
  state_file: "monitor_state.json"
  delays:
    min: 0.6
    max: 2.5
